/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistematiendaropa;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ROJAS
 */
public class FrameSistemaRopa extends javax.swing.JFrame {

    /**
     * Creates new form FrameSistemaRopa
     */
    public FrameSistemaRopa() {
        initComponents();
        this.tableDetalles.setModel(modelo);
        this.modelo.addColumn("Nacionalidad");
        this.modelo.addColumn("Género");
        this.modelo.addColumn("Tallas");
        this.modelo.addColumn("Prendas");
        this.modelo.addColumn("Cantidad");
        this.modelo.addColumn("Precio Unitario");
        this.modelo.addColumn("Total a pagar");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultTableModel modelo = new DefaultTableModel();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        cbNacionalidad = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        rbHombre = new javax.swing.JRadioButton();
        rbMujer = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        cbTallas = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtPrenda = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnGenerarCompra = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        txtTotal = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableDetalles = new javax.swing.JTable();
        btnLimpiarTabla = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnNeto = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        txtNeto = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("SISTEMA GESTIÓN TIENDA ROPA");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("DESCUENTOS Y/O PROMOCIONES"));

        jLabel2.setText("Nacional");

        jLabel3.setText("HOMBRE TALLA: S=0.05, M=0.07, L=0.10");

        jLabel4.setText("MUJER TALLA   : S=0.04, M= 0.09, L=0.12");

        jLabel5.setText("Extranjeros");

        jLabel6.setText("HOMBRE TALLA: S=0.04, M=0.09, L=0.12");

        jLabel7.setText("MUJER TALLA   : S=0.05, M=0.07, L=0.10");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("REALIZAR COMPRA"));

        jLabel8.setText("Nacionalidad");

        cbNacionalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "Colombiano", "Extranjero" }));
        cbNacionalidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbNacionalidadActionPerformed(evt);
            }
        });

        jLabel9.setText("Género:");

        rbHombre.setText("Hombre");
        rbHombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbHombreActionPerformed(evt);
            }
        });

        rbMujer.setText("Mujer");

        jLabel10.setText("Tallas");

        cbTallas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "S", "M", "L" }));

        jLabel11.setText("Prenda");

        txtPrenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrendaActionPerformed(evt);
            }
        });

        jLabel12.setText("Cantidad");

        txtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCantidadActionPerformed(evt);
            }
        });

        jLabel14.setText("Total a Pagar: ");

        btnGenerarCompra.setText("GENERAR COMPRA");
        btnGenerarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarCompraActionPerformed(evt);
            }
        });

        btnLimpiar.setText("LIMPIAR");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        txtTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalActionPerformed(evt);
            }
        });

        txtPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrecioActionPerformed(evt);
            }
        });

        jLabel13.setText("Precio");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cbNacionalidad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(105, 105, 105)
                                .addComponent(jLabel10)
                                .addGap(60, 60, 60)
                                .addComponent(jLabel11)
                                .addGap(32, 32, 32)
                                .addComponent(jLabel12))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(rbHombre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbMujer)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbTallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(btnGenerarCompra)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel14)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbNacionalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbHombre)
                    .addComponent(rbMujer)
                    .addComponent(cbTallas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerarCompra)
                    .addComponent(btnLimpiar)
                    .addComponent(jLabel14)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalle de compras"));

        tableDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableDetalles);

        btnLimpiarTabla.setText("LIMPIAR TABLA");
        btnLimpiarTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarTablaActionPerformed(evt);
            }
        });

        btnQuitar.setText("QUITAR COMPRA");
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });

        btnNeto.setText("NETO A PAGAR");
        btnNeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNetoActionPerformed(evt);
            }
        });

        jLabel15.setText("Neto a pagar: $");

        txtNeto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNetoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarTabla)
                .addGap(30, 30, 30)
                .addComponent(btnQuitar)
                .addGap(39, 39, 39)
                .addComponent(btnNeto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtNeto, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNeto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(btnNeto)
                    .addComponent(btnQuitar)
                    .addComponent(btnLimpiarTabla))
                .addGap(113, 113, 113))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(323, 323, 323)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNetoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNetoActionPerformed

    private void txtTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTotalActionPerformed

    private void cbNacionalidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbNacionalidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbNacionalidadActionPerformed

    private void txtPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrecioActionPerformed

    private void txtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCantidadActionPerformed

    private void rbHombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbHombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbHombreActionPerformed

    private void btnGenerarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarCompraActionPerformed
        // TODO add your handling code here:
        descuentos_hombres_colombianos();
        descuentos_mujeres_colombianas();
        descuentos_hombres_extranjeros();
        descuentos_mujeres_extranjeras();
        //LLAVE ABREN Y CIERRAN
        if(rbHombre.isSelected()){
            this.modelo.addRow(new Object[]{this.cbNacionalidad.getSelectedItem(),"Hombre",
                this.cbTallas.getSelectedItem(), this.txtPrenda.getText(), this.txtCantidad.getText(),
                this.txtPrecio.getText()});
        }
        else if(rbMujer.isSelected()){
            this.modelo.addRow(new Object[]{this.cbNacionalidad.getSelectedItem(),"Mujer",
                this.cbTallas.getSelectedItem(), this.txtPrenda.getText(), this.txtCantidad.getText(),
                this.txtPrecio.getText()});
        }
    }//GEN-LAST:event_btnGenerarCompraActionPerformed

    private void txtPrendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrendaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrendaActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        this.cbNacionalidad.setSelectedIndex(0);
        if(rbHombre.isSelected()){
            
        }
        if(rbMujer.isSelected()){
            
        }
        this.cbTallas.setSelectedIndex(0);
        this.txtPrenda.setText("");
        this.txtCantidad.setText("");
        this.txtPrecio.setText("");
        this.txtTotal.setText("");
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        // TODO add your handling code here:
        modelo.removeRow(this.tableDetalles.getSelectedRow());
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnLimpiarTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarTablaActionPerformed
        // TODO add your handling code here:
        int x = this.modelo.getRowCount();
        for (int y = 0; y < 10; y++) {
            this.modelo.removeRow(0);
        }
        this.txtNeto.setText("");
    }//GEN-LAST:event_btnLimpiarTablaActionPerformed

    private void btnNetoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNetoActionPerformed
        // TODO add your handling code here:
        double sumatoria;
        double sumatoria1 = 0;
        int totalrow = tableDetalles.getRowCount();
        totalrow-=1;
        for (int i = 0; i < (totalrow); i++) {
            sumatoria = Double.parseDouble(String.valueOf(tableDetalles.getValueAt(i, 6)));
            sumatoria1 += sumatoria; 
        }
        txtNeto.setText("$. "+String.valueOf(sumatoria1));
    }//GEN-LAST:event_btnNetoActionPerformed
    public void descuentos_hombres_extranjeros(){
        double cantidad_s, precio_s, total_s, desc_s = 0.04;
        double cantidad_m, precio_m, total_m, desc_m = 0.09;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        //SELECCIONA S
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbHombre.isSelected()){
                if(cbTallas.getSelectedIndex()==1){
                    cantidad_s = Double.parseDouble(this.txtCantidad.getText());
                    precio_s = Double.parseDouble(this.txtPrecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s) * desc_s);
                    this.txtTotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SELECCIONA M
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbHombre.isSelected()){
                if(cbTallas.getSelectedIndex()==2){
                    cantidad_m = Double.parseDouble(this.txtCantidad.getText());
                    precio_m = Double.parseDouble(this.txtPrecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m) * desc_m);
                    this.txtTotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SELECCIONA L
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbHombre.isSelected()){
                if(cbTallas.getSelectedIndex()==3){
                    cantidad_l = Double.parseDouble(this.txtCantidad.getText());
                    precio_l = Double.parseDouble(this.txtPrecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l) * desc_l);
                    this.txtTotal.setText(String.valueOf(total_l));
                }
            }
        }
    }
    public void descuentos_mujeres_extranjeras(){
        double cantidad_s, precio_s, total_s, desc_s = 0.04;
        double cantidad_m, precio_m, total_m, desc_m = 0.09;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        //SELECCIONA S
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbMujer.isSelected()){
                if(cbTallas.getSelectedIndex()==1){
                    cantidad_s = Double.parseDouble(this.txtCantidad.getText());
                    precio_s = Double.parseDouble(this.txtPrecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s) * desc_s);
                    this.txtTotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SELECCIONA M
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbMujer.isSelected()){
                if(cbTallas.getSelectedIndex()==2){
                    cantidad_m = Double.parseDouble(this.txtCantidad.getText());
                    precio_m = Double.parseDouble(this.txtPrecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m) * desc_m);
                    this.txtTotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SELECCIONA L
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbMujer.isSelected()){
                if(cbTallas.getSelectedIndex()==3){
                    cantidad_l = Double.parseDouble(this.txtCantidad.getText());
                    precio_l = Double.parseDouble(this.txtPrecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l) * desc_l);
                    this.txtTotal.setText(String.valueOf(total_l));
                }
            }
        }
    }
    public void descuentos_hombres_colombianos(){
        double cantidad_s, precio_s, total_s, desc_s = 0.04;
        double cantidad_m, precio_m, total_m, desc_m = 0.09;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        //SELECCIONA S
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbHombre.isSelected()){
                if(cbTallas.getSelectedIndex()==1){
                    cantidad_s = Double.parseDouble(this.txtCantidad.getText());
                    precio_s = Double.parseDouble(this.txtPrecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s) * desc_s);
                    this.txtTotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SELECCIONA M
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbHombre.isSelected()){
                if(cbTallas.getSelectedIndex()==2){
                    cantidad_m = Double.parseDouble(this.txtCantidad.getText());
                    precio_m = Double.parseDouble(this.txtPrecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m) * desc_m);
                    this.txtTotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SELECCIONA L
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbHombre.isSelected()){
                if(cbTallas.getSelectedIndex()==3){
                    cantidad_l = Double.parseDouble(this.txtCantidad.getText());
                    precio_l = Double.parseDouble(this.txtPrecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l) * desc_l);
                    this.txtTotal.setText(String.valueOf(total_l));
                }
            }
        }
    }
    public void descuentos_mujeres_colombianas(){
        double cantidad_s, precio_s, total_s, desc_s = 0.04;
        double cantidad_m, precio_m, total_m, desc_m = 0.09;
        double cantidad_l, precio_l, total_l, desc_l = 0.12;
        //SELECCIONA S
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbMujer.isSelected()){
                if(cbTallas.getSelectedIndex()==1){
                    cantidad_s = Double.parseDouble(this.txtCantidad.getText());
                    precio_s = Double.parseDouble(this.txtPrecio.getText());
                    total_s = (precio_s * cantidad_s)-((cantidad_s * precio_s) * desc_s);
                    this.txtTotal.setText(String.valueOf(total_s));
                }
            }
        }
        //SELECCIONA M
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbMujer.isSelected()){
                if(cbTallas.getSelectedIndex()==2){
                    cantidad_m = Double.parseDouble(this.txtCantidad.getText());
                    precio_m = Double.parseDouble(this.txtPrecio.getText());
                    total_m = (precio_m * cantidad_m)-((cantidad_m * precio_m) * desc_m);
                    this.txtTotal.setText(String.valueOf(total_m));
                }
            }
        }
        //SELECCIONA L
        if(cbNacionalidad.getSelectedIndex()==2){
            if(this.rbMujer.isSelected()){
                if(cbTallas.getSelectedIndex()==3){
                    cantidad_l = Double.parseDouble(this.txtCantidad.getText());
                    precio_l = Double.parseDouble(this.txtPrecio.getText());
                    total_l = (precio_l * cantidad_l)-((cantidad_l * precio_l) * desc_l);
                    this.txtTotal.setText(String.valueOf(total_l));
                }
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameSistemaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameSistemaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameSistemaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameSistemaRopa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameSistemaRopa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarCompra;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnLimpiarTabla;
    private javax.swing.JButton btnNeto;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cbNacionalidad;
    private javax.swing.JComboBox<String> cbTallas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton rbHombre;
    private javax.swing.JRadioButton rbMujer;
    private javax.swing.JTable tableDetalles;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtNeto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtPrenda;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
